# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'K5Tool' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for K5Tool
  pod 'BinarySwift'
  pod 'Bitter'

  target 'K5ToolTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'K5ToolUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
